Update docs for typescript sdk for browser
Amplitude-Developer-Docs/amplitude-dev-center pull request #117
Opened 2022-06-24 00:43 UTC by kevinpagtakhan

# Dev Docs PR

## Description

Update Typescript SDK for Browser to include more complete and accurate information.

## Deadline

🤔 

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

2022-06-24 05:25 UTC, kevinpagtakhan commented
This is the page the PR modified: https://pr-117.d19s7xzcva2mw3.amplifyapp.com/data/sdks/typescript-browser/#sdks

2022-06-27 11:56 UTC, caseyamp requested changes
Great work. @kevinpagtakhan -- I made a few changes to follow our formatting standards. After you accept them you're free to merge!

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +Amplitude supports assigning users to groups and performing queries such as Count by Distinct on those groups. An example would be if you want to group your users based on what organization they are
```suggestion
--8<-- "includes/groups-intro-paragraph.md"
```

We have a reusable that contains all this.

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +
```suggestion
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +When setting groups, you will need to define a groupType and groupName(s). In the above example, 'orgId' is the groupType and the values '10' and '15' are groupName(s). Another example of a groupType
```suggestion
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +product_id (optional) | string | An identifier for the product. We recommend something like the Google Play Store product ID. | null
```suggestion
|`product_id` | Optional. String. An identifier for the product. We recommend something like the Google Play Store product ID. Defaults to null. |
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +Name |  Type  |Description | Default
```suggestion
|Name | Description |
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +-----|-------|--------------|--------
```suggestion
|-----|-------|
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +quantity *(required)* | int| The quantity of products purchased. Note: revenue = quantity * price | 1
```suggestion
|`quantity` | Required. Int. The quantity of products purchased. Note: revenue = quantity * price. Defaults to 1|
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +revenue_type (optional, *required for revenue verification*) | String| The type of revenue (e.g. tax, refund, income). | null
```suggestion
|`revenue_type` | Optional, but required for revenue verification. String. The type of revenue (e.g. tax, refund, income).  Defaults to null.|
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +receipt (optional) | String| The receipt identifier of the revenue. | null
```suggestion
|`receipt`| Optional. String. The receipt identifier of the revenue. Defaults to null|
```

2022-06-27 11:56 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +properties (optional) | JSONObject| An object of event properties to include in the revenue event.| null
```suggestion
|`properties`| Optional. JSONObject. An object of event properties to include in the revenue event. Defaults to null.
```

2022-06-28 06:22 UTC, kevinpagtakhan commented
@caseyamp i have committed the changes you suggested but the preview check isn't completing and I'm unable to merge. can you take a look please? thank you

2022-06-28 11:45 UTC, caseyamp approved these changes

2022-06-28 11:45 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +!!!warning "SDK Resources"
```suggestion
!!!note 
```

2022-06-28 11:45 UTC, caseyamp commented on docs/data/sdks/typescript-browser.md
> +#### Enrichment type plugin
```suggestion
##### Enrichment type plugin
```

2022-06-28 16:52 UTC, merged