Add considerations for migration doc
Amplitude-Developer-Docs/amplitude-dev-center pull request #205
Opened 2022-08-15 14:31 UTC by caseyamp

# Dev Docs PR

## Description

Add considerations for migration

## Deadline

Casual. 

## Change type

- [X] Doc update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

2022-08-15 14:35 UTC, caseyamp commented
Fixes DDI-126

2022-08-18 07:38 UTC, caseyamp commented
@justin-fiedler can you take a peek at this and LMK if it's what you had in mind?

2022-08-23 15:14 UTC, justin-fiedler requested changes

2022-08-23 15:14 UTC, justin-fiedler commented on docs/data/ampli/migration.md
> +- The `context` parameter isn't supported in Ampli. This was originally based on per Source Templates which is a feature that is eprecated. To add additional data on each event you can do so by creat
*deprecated

2022-08-23 15:14 UTC, justin-fiedler commented on docs/data/ampli/migration.md
> +With all the benefits of type-safety, linting, and data validation to make sure that your analytics are accurate and trustworthy.
Might read easier if we combing this with the blurb above:

> After you import your tracking plan into Amplitude Data, this event becomes the following, with all the benefits of type-safety, linting, and data validation to make sure that your analytics are accurate and trustworthy.

2022-08-23 22:15 UTC, justin-fiedler approved these changes

2022-08-24 11:47 UTC, merged