complete the quick guide example
Amplitude-Developer-Docs/amplitude-dev-center pull request #275
Opened 2022-09-15 00:48 UTC by yuhao900914

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

2022-09-15 13:48 UTC, justin-fiedler requested changes
JS/TS changes look good. Can you please also fix the paratheses alignment in Python and ReactNative examples.

https://amplitude.slack.com/archives/C02E1H87E2C/p1663163693714989?thread_ts=1663106803.691659&cid=C02E1H87E2C

<img width="307" alt="image" src="https://user-images.githubusercontent.com/5790872/190420832-cfd09915-d1f5-4499-88cc-6cb797878a9b.png">

```
amplitude.track(BaseEvent(
          event_type="type of event",
          user_id="USER_ID",
          device_id="DEVICE_ID",
          event_properties={
                "source": "notification"
          }
))
```

or 

```
amplitude.track(
       BaseEvent(
          event_type="type of event",
          user_id="USER_ID",
          device_id="DEVICE_ID",
          event_properties={
                "source": "notification"
          }
      )
)
```

2022-09-16 00:29 UTC, liuyang1520 approved these changes

2022-09-16 00:29 UTC, liuyang1520 commented on docs/data/sdks/index.md
> +        ampli.yourEventType("ampli-user-id", {
Minor, double quote -> single quote?

2022-09-16 00:29 UTC, liuyang1520 commented on docs/data/sdks/index.md
> +            stringProp: "Strongly typed property",
Ditto?

2022-09-20 16:53 UTC, caseyamp commented
@yuhao900914 are we waiting on anything here?

2022-09-20 17:16 UTC, yuhao900914 commented
> @yuhao900914 are we waiting on anything here?

2022-09-20 17:18 UTC, justin-fiedler requested changes
1. missing tab in RN TS example:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/5790872/191322508-b3dbbc0f-9edc-4594-bcdc-bb0366b1bace.png">
2. JRE Java 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/5790872/191322748-c3302b5f-3af4-441a-974a-edb3230a7c2f.png">
3. Browser standardize to single quote:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/5790872/191323045-cbab6838-60b9-409e-b721-f8865eb10cc8.png">

2022-09-20 17:18 UTC, justin-fiedler commented on docs/data/sdks/index.md
> +            YourEventType(
nit: align parentheses

2022-09-20 18:14 UTC, closed without merging