Update Intercom-cohort.md
Amplitude-Developer-Docs/amplitude-dev-center pull request #276
Opened 2022-09-15 01:06 UTC by sina-jamshidi

Updating cohort export docs with important information for customers

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

2022-09-15 12:23 UTC, caseyamp requested changes
Just a little nit for style guide, thanks @sina-jamshidi

2022-09-15 12:23 UTC, caseyamp commented on docs/data/destinations/intercom-cohort.md
> +    Users are exported based on their **User Id**. Users must already exist on Intercom with corresponding User Ids in order to be properly synced
```suggestion
    Users are exported based on their **user ID**. Users must already exist in Intercom with corresponding user IDs in order to be properly synced
```

2022-09-15 22:36 UTC, sina-jamshidi commented on docs/data/destinations/intercom-cohort.md
> +    Users are exported based on their **User Id**. Users must already exist on Intercom with corresponding User Ids in order to be properly synced
Great thanks Casey!

2022-09-16 12:44 UTC, caseyamp approved these changes

2022-09-16 12:47 UTC, caseyamp commented
@sina-jamshidi merge when ready!

2022-09-21 19:06 UTC, merged