Amp 58497 go ampli developer doc
Amplitude-Developer-Docs/amplitude-dev-center pull request #289
Opened 2022-09-23 22:51 UTC by justin-fiedler

# Amplitude Developer Docs PR

## Description
* Go doc updates for latest changes
* Go Ampli docs

## Change type
- [x] Doc update.
- [x] New documentation.

@amplitude-dev-docs
@caseyamp

2022-09-23 23:29 UTC, yuhao900914 requested changes

2022-09-23 23:29 UTC, yuhao900914 commented on docs/data/sdks/go/ampli.md
> +title: Go Ampli Wrapper (Alpha)
Change this to Beta?

2022-09-23 23:29 UTC, yuhao900914 commented on docs/data/sdks/go/ampli.md
> +!!!alpha "Go Ampli Resources (Alpha)"
Remove the alpha tag?

2022-09-23 23:29 UTC, yuhao900914 commented on docs/data/sdks/go/index.md
> +!!!alpha "Go SDK Resources (Alpha)"
Alpha tag

2022-09-23 23:29 UTC, yuhao900914 commented on docs/data/sdks/go/ampli.md
> +    "<your-module-name>/ampli"
extra line above?

2022-09-24 00:48 UTC, liuyang1520 approved these changes

2022-09-24 00:48 UTC, liuyang1520 commented on docs/data/sdks/go/index.md
> +    EventType:    "Button Clicked",
Minor, alignment?
```
UserID:    "user-id",
EventType: "Button Clicked",
```

2022-09-24 01:06 UTC, yuhao900914 approved these changes

2022-09-24 01:08 UTC, merged