chore: updated SDK versions/snippets
Amplitude-Developer-Docs/amplitude-dev-center pull request #553
Opened 2023-01-30 13:54 UTC by falconandy

# Amplitude Developer Docs PR

## Description

Updated SDK versions/snippets

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

2023-01-30 13:59 UTC, caseyamp commented
@falconandy you can ignore the link check warnings

2023-02-04 00:00 UTC, justin-fiedler requested changes

2023-02-06 13:15 UTC, falconandy commented on docs/data/sdks/java/ampli.md
> +    implementation 'com.amplitude:java-sdk:1.+'
I think, versions in the documentation are used by new users mostly. `1.+` version will still install the latest available version for them. 
Maybe documentation sections (like `Middleware support`) should have some badges with supported version - like `Available from version 1.6`

2023-02-07 13:38 UTC, falconandy commented on docs/data/sdks/java/ampli.md
> +    implementation 'com.amplitude:java-sdk:1.+'
Updated based on https://github.com/amplitude/javascript/blob/master/server/packages/orbit/apps/stargate-client/src/codegen/sdk-versions.ts

2023-02-08 16:10 UTC, justin-fiedler commented on docs/data/sdks/java/ampli.md
> +    implementation 'com.amplitude:java-sdk:[1.8.0,2.0)'
I think this needs to be `[1.10.0,2)` for Plan information.

2023-02-08 16:14 UTC, justin-fiedler approved these changes

2023-02-08 16:42 UTC, justin-fiedler commented on docs/data/sdks/java/ampli.md
> +    implementation 'com.amplitude:java-sdk:[1.8.0,2.0)'
Nevermind, plan is in 1.8.0

2023-02-08 16:42 UTC, merged