Removes beta label from new react native sdk
Amplitude-Developer-Docs/amplitude-dev-center pull request #569
Opened 2023-02-02 22:27 UTC by kevinpagtakhan

# Amplitude Developer Docs PR

## Description

Removes beta label from new react native sdk

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

2023-02-02 23:20 UTC, justin-fiedler requested changes

2023-02-02 23:20 UTC, justin-fiedler commented on mkdocs.yml
>          - Ampli Codegen (Beta): data/sdks/typescript-react-native/ampli.md
Can you please remove Beta from RN Ampli as well

2023-02-03 18:07 UTC, kevinpagtakhan commented on mkdocs.yml
> +        - Ampli Codegen: data/sdks/typescript-react-native/ampli.md
cc @justin-fiedler

2023-02-03 23:16 UTC, justin-fiedler approved these changes

2023-02-03 23:29 UTC, merged