Re-word manual session_id sentence
Amplitude-Developer-Docs/amplitude-dev-center pull request #651
Opened 2023-03-13 01:53 UTC by markfoo

Reword last session under 'Sessions' to reflect usage of HTTP APIs for seeing session IDs manually

# Amplitude Developer Docs PR

## Description

Reword last session under 'Sessions' to reflect usage of HTTP APIs for seeing session IDs manually

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-03-17 16:57 UTC, bgiori approved these changes

2023-03-17 16:58 UTC, bgiori requested changes

2023-07-31 21:30 UTC, kevinpagtakhan commented
@markfoo do we still need this PR?

2023-09-19 17:49 UTC, markzegarelli commented
Closing this in preparation of migrating the repository.

2023-09-19 17:49 UTC, closed without merging