fix configuration nits and others
Amplitude-Developer-Docs/amplitude-dev-center pull request #670
Opened 2023-03-22 17:24 UTC by yuhao900914

# Amplitude Developer Docs PR

## Description
1. fixed some configuration nits.
2. add web attribution and page view tracking on the browser SDK.  There has an update on Browser SDK. Right now for web attribution and pageview tracking, it's using the plugins internally. Also, we mentioned the browser SDK web attribution parameter in the Browser SDK Migration Guide, but there is no place to explain how it works. (Check this [Github issue](https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/issues/643)). We should list the attribution configurations in the browser SDK.

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-03-22 19:03 UTC, justin-fiedler requested changes
Looks good. See nits.

2023-03-22 19:03 UTC, justin-fiedler commented on docs/data/sdks/marketing-analytics-browser/index.md
> +|`attribution.initialEmptyValue`| `string`. Custom the init empty value for attribution related user properties to any string value | `EMPTY` |
```suggestion
|`attribution.initialEmptyValue`| `string`. Customize the initial empty value for attribution related user properties to any string value | `EMPTY` |
```

2023-03-22 19:03 UTC, justin-fiedler commented on docs/data/sdks/typescript-browser/migration.md
> -|`config.plan.versionId`|`config.plan.versionId`|
🙏

2023-03-22 19:03 UTC, justin-fiedler commented on docs/data/sdks/typescript-browser/migration.md
> +|`config.saveParamsReferrerOncePerSession`|`config.attribution.trackNewCampaigns`. Opposite with `saveParamsReferrerOncePerSession`. See [configuration](../#configuration). |
```suggestion
|`config.saveParamsReferrerOncePerSession`|`config.attribution.trackNewCampaigns`. Opposite of `saveParamsReferrerOncePerSession`. See [configuration](../#configuration). |
```

2023-03-22 21:50 UTC, Mercy811 approved these changes

2023-03-22 21:50 UTC, Mercy811 commented on docs/data/sdks/typescript-browser/index.md
> +
Do we need to provide an example of how to config attributions?

2023-03-23 18:52 UTC, justin-fiedler approved these changes

2023-03-23 23:05 UTC, merged