Update webhook streaming docs
Amplitude-Developer-Docs/amplitude-dev-center pull request #676
Opened 2023-03-28 18:56 UTC by sina-jamshidi

# Amplitude Developer Docs PR
Updated Webhook docs to include user forwarding and to match new docs

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ x ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ x ] My documentation follows the style guidelines of this project.
- [ x ] I previewed my documentation on a local server using `mkdocs serve`.
- [ x ] Running `mkdocs serve` didn't generate any failures.
- [ x ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-03-28 19:03 UTC, bgiori requested changes

2023-03-28 19:06 UTC, sina-jamshidi commented on docs/data/destinations/webhooks-streaming.md
> +Under **Send Users**, make sure the toggle is enabled ("Users are sent to Webhook") if you want to stream users and their properties to the webhook. When enabled, users are sent to the webhook when a
oops good catch!

2023-03-29 15:18 UTC, bgiori approved these changes

2023-03-30 23:28 UTC, daniel-beer approved these changes

2023-03-31 10:42 UTC, merged