Android update
Amplitude-Developer-Docs/amplitude-dev-center pull request #706
Opened 2023-04-15 01:12 UTC by yuhao900914

# Amplitude Developer Docs PR

## Description

Based on the Android doc, https://support.google.com/googleplay/android-developer/answer/6048248?hl=en and also the customer question from [Discourse](https://discourse.amplitude.com/t/ad-id-declaration-in-the-manifest-for-android-sdk/10198/2), I added the ADID permission on both Android and Kotlin side. 

<img width="746" alt="Screen Shot 2023-04-14 at 6 11 32 PM" src="https://user-images.githubusercontent.com/13028329/232175875-f7dd7faa-ed28-4e22-85a7-af5d3636c77d.png">

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-04-15 04:16 UTC, bgiori requested changes

2023-04-15 04:16 UTC, bgiori commented on docs/data/ampli/middleware.md
> +| `event.event_type` | string ||
```suggestion
| `event.event_type` | string |
```

2023-04-18 15:14 UTC, justin-fiedler approved these changes

2023-04-18 15:14 UTC, justin-fiedler commented on docs/data/sdks/android-kotlin/index.md
> +    As of April 1, 2022, Google allows users to opt out of Ad ID tracking. Ad ID may return null or error. You can use am alternative ID called [App Set ID](#app-set-id), which is unique to every app
nit: could be worth it to convert this to an include so we can update it in a single place

2023-04-18 20:16 UTC, bgiori approved these changes

2023-04-18 21:56 UTC, merged