Added Cohorts to User.com
Amplitude-Developer-Docs/amplitude-dev-center pull request #715
Opened 2023-04-18 05:21 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-04-18 20:15 UTC, bgiori requested changes

2023-04-18 20:15 UTC, bgiori commented on mkdocs.yml
> +        - Userlist: data/destinations/user.com-cohort.md
```suggestion
        - User.com: data/destinations/user.com-cohort.md
```

2023-04-18 20:15 UTC, bgiori commented on docs/data/destinations/user.com-cohort.md
> +### Userflow setup
```suggestion
### User.com setup
```

2023-04-21 07:44 UTC, Brandoncharleskhoo1 commented on mkdocs.yml
> +        - Userlist: data/destinations/user.com-cohort.md
Thanks for catching this Brian!

2023-04-22 01:45 UTC, bgiori approved these changes

2023-04-22 02:42 UTC, merged