AMP-74857 Add support link
Amplitude-Developer-Docs/amplitude-dev-center pull request #744
Opened 2023-05-09 19:12 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

- Add a support link at the bottom of each page
- Track [support request](https://data.amplitude.com/amplitude/Developer%20Docs%20(Prod)/events/main/latest/support%20request?view=All&tab=DETAILS&propertyValidityFilter=All%2520Properties) event 
<img width="695" alt="Screen Shot 2023-05-09 at 12 08 08" src="https://github.com/Amplitude-Developer-Docs/amplitude-dev-center/assets/31029607/33d3c76b-c571-43b6-afcd-02694c9eaff0">

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-05-09 20:17 UTC, yuhao900914 approved these changes

2023-05-09 23:36 UTC, justin-fiedler requested changes

2023-05-09 23:36 UTC, justin-fiedler commented on overrides/partials/content.html
> +  <p>Still have questions? Ask them in the <a id="linkToCommunityHelp" href="https://community.amplitude.com" onclick="amplitude.getInstance().logEvent('Link Click', eventProperties)">Community</a> o
```suggestion
  <p>Still have questions? Ask them in the <a id="linkToCommunityHelp" href="https://community.amplitude.com" onclick="amplitude.getInstance().logEvent('Link Click', eventProperties)">Community</a> or <a  href="https://support.amplitude.com/" onclick="trackClickSupportRequest()">submit a request</a>.
```

2023-05-10 00:15 UTC, justin-fiedler approved these changes

2023-05-16 06:05 UTC, closed without merging