Create movable-ink-event-streaming.md
Amplitude-Developer-Docs/amplitude-dev-center pull request #913
Opened 2023-08-18 01:05 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-08-18 17:05 UTC, markzegarelli requested changes
Hi @Brandoncharleskhoo1 Some formatting and verbiage suggestions here.

2023-08-18 17:05 UTC, markzegarelli commented on docs/data/destinations/movable-ink-event-streaming.md
> +10. (optional) In **Select additional properties**, select any more user properties you want to send to MovableInk. If you don't select any properties here, Amplitude doesn't send any. _Transformed u
```suggestion
10. (optional) In the **Select additional properties** section, select any additional user properties you want to send to Movable Ink. Amplitude sends only the properties you select here. This integration does not support transformed user properties. 
```

2023-08-18 17:05 UTC, markzegarelli commented on docs/data/destinations/movable-ink-event-streaming.md
> +- **Analyzing and Segmenting Users:** With Amplitude's analytics capabilities, you can analyze user behavior, identify patterns, and create segments based on specific actions or attributes. For examp
```suggestion
- **Analyze and Segment Users:** With Amplitude's analytics capabilities, you can analyze user behavior, identify patterns, and create segments based on specific actions or attributes. For example, you may identify a segment of users who have recently made a purchase or visited a specific page.
```

2023-08-18 17:05 UTC, markzegarelli commented on docs/data/destinations/movable-ink-event-streaming.md
> +- **Sending Event Data to Movable Ink:** Once you have defined your desired segments, you can set up an integration or data pipeline to send the relevant event data from Amplitude to Movable Ink. Thi
```suggestion
- **Send Event Data to Movable Ink:** After you define your segments, you can configure an integration or data pipeline to send the relevant event data from Amplitude to Movable Ink. You can do this with APIs, web hook integrations, or other methods supported by both platforms.
```

2023-08-24 20:44 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/movable-ink-event-streaming.md
> +To configure an Event Streaming integration from Amplitude to Movable Ink, you must fulfill the following prerequisites from Movable Ink:
Made the changes.

2023-08-24 20:44 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/movable-ink-event-streaming.md
> +- You need to be an admin of a paid Planhat plan to enable this integration.
Thanks for catching this.

2023-09-21 23:28 UTC, merged