AMP-83919 [BigQueryGA4Import] Add notes of BigQuery import to all places mentioning GA4
Amplitude-Developer-Docs/amplitude-dev-center pull request #960
Opened 2023-09-06 01:18 UTC by bh202205

# Amplitude Developer Docs PR

## Description

This PR adds notes of BigQuery import to all places mentioning GA4 to track customers/users attention for our support of GA4 import via BigQuery import.

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-09-06 01:25 UTC, joez2 approved these changes
Previewed the change. LGTM. Thanks for updating the dev docs!

2023-09-06 02:14 UTC, markzegarelli requested changes
Thanks @bh202205!

I edited the content to align with our style elsewhere.

One question I have is, "BigQuery Import for GA4 Beta"...does this mean that we are working on a beta of the BigQuery Import feature? Or will the BigQuery Import feature work on a beta version of GA4?

2023-09-06 02:14 UTC, markzegarelli commented on docs/data/destinations/google-analytics-4-firebase.md
> +    We are working on BigQuery Import for GA4 Beta. Please feel free to reach out to <dwh+GA4beta@amplitude.com>. In addition, click [here](/data/sources/bigquery) to view how you can import BigQuery
```suggestion
    Amplitude is working on BigQuery Import for GA4 Beta. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to Amplitude, see the [BigQuery Source documentation](/data/sources/bigquery).
```

2023-09-06 02:14 UTC, markzegarelli commented on docs/data/destinations/google-analytics-4-gtag.md
> +    We are working on BigQuery Import for GA4 Beta. Please feel free to reach out to <dwh+GA4beta@amplitude.com>. In addition, click [here](/data/sources/bigquery) to view how you can import BigQuery
```suggestion
    Amplitude is working on BigQuery Import for GA4 Beta. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to Amplitude, see the [BigQuery Source documentation](/data/sources/bigquery).
```

2023-09-06 02:14 UTC, markzegarelli commented on docs/data/tutorials/migrating-from-google-analytics/index.md
> +    We are working on BigQuery Import for GA4 Beta. Please feel free to reach out to <dwh+GA4beta@amplitude.com>. In addition, click [here](/data/sources/bigquery) to view how you can import BigQuery
```suggestion
    Amplitude is working on BigQuery Import for GA4 Beta. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to Amplitude, see the [BigQuery Source documentation](/data/sources/bigquery).
```

2023-09-07 05:23 UTC, bh202205 commented
> Thanks @bh202205!
> 
> I edited the content to align with our style elsewhere.
> 
> One question I have is, "BigQuery Import for GA4 Beta"...does this mean that we are working on a beta of the BigQuery Import feature? Or will the BigQuery Import feature work on a beta version of GA4?

@markzegarelli Thank you for all your comments and just updated the files! 

To answer your question, let me give you some context. BigQuery is one of the popular data warehouses that our customers use and it's a google cloud product. We have a data warehouse integration called: BigQuery Import, which allow customers to import data from their BigQuery. GA4 (google analytics 4) is one of our competitors and what we are building is an kind of new integration that customers to import their GA4 data to Amplitude based on our existing BigQuery Import.

Let me know if this makes sense to you. Thank again!

2023-09-07 20:39 UTC, markzegarelli commented on docs/data/sources/bigquery.md
> +    Amplitude is working on BigQuery Import for GA4 Beta. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to
```suggestion
    Amplitude is working on a beta version of BigQuery Import for GA4. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to Amplitude, see the [BigQuery Source documentation](/data/sources/bigquery).
```

2023-09-07 20:39 UTC, markzegarelli commented on docs/data/tutorials/migrating-from-google-analytics/index.md
> +    Amplitude is working on BigQuery Import for GA4 Beta. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to
```suggestion
    Amplitude is working on a beta version of BigQuery Import for GA4. Contact [dwh+GA4beta@amplitude.com](mailto:dwh+GA4beta@amplitude.com) to learn more. For more information about importing BiqQuery data in to Amplitude, see the [BigQuery Source documentation](/data/sources/bigquery).
```

2023-09-07 21:01 UTC, merged